
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td id="lefttd">
            <div id="left-menu">
                <? Admin_View_Helper_Configs_ConfigsMenu::MakeConfigsMenu(); ?>
            </div>       
        </td>
        <td id="righttd">
            <div id="acontent">
                
                <? if ($this->ok): ?>
                    <div class="block-ok"><?= $this->ok; ?></div>
                <? endif; ?>

                <? if ($this->neok): ?>
                    <div class="block-error"><?= $this->neok; ?></div>
                <? endif; ?>
                <ul id="tabs">
                    <li title="rus" class="active"><h1>   <? if ($_GET['id'] > 0): ?>Редактирование языка<? else: ?>Создание языка<? endif; ?></h1></li>
                </ul>

                <div id="tabs-content-list">
                    <div class="tabs-item edit-and-add" id="rus">

                        <form enctype="multipart/form-data" id="<?= $this->form->getId() ?>" method="POST" action="<?= $this->form->getAction() ?>">

                            <? foreach ($this->form as $element): ?>
                                <?= $element ?>
                                <? if ($element->getName() == 'language_name'): ?>

                                    <dt><label>Картинка [Изображение автоматически не подстраивается]:</label></dt>

                                    <dd>
                                        <div class="input-image">
                                            <? if (strlen($this->data->language_pic) > 4): ?>
                                                <img src="<?=$this->baseUrl();?>/<?= $this->data->language_pic; ?>" />
                                                
                                            <? endif; ?>
                                        </div>
                                        <div class="ffile">
                                            <input type="file" name="Filedata" class="bfile" size="2" />
                                            <a href="#" class="sbutton">Выбрать</a>
                                        </div>
                                    </dd>
                                <? endif; ?>

                            <? endforeach ?>
                            <div class="save_page">
                                <a href="admin/language/" class="sbutton">Отмена</a>
                                <input type="submit" name="#" value="<? if ($_GET['id'] > 0): ?>Сохранить<? else: ?>Создать<? endif; ?>" class="sbutton" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </td>
    </tr>
</table>
