<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8">
        <title>UDS™ CMS v2.0.2</title>
        <base href="<?= $this->baseUrl(); ?>/">
        <?php
        $this->headLink()->appendStylesheet('/adm_template/css/reset_style.css');
        $this->headLink()->appendStylesheet('/adm_template/css/jquery.fancybox-1.3.4.css');
        $this->headLink()->appendStylesheet('/adm_template/css/jquery-ui-1.8.21.custom.css');
        $this->headLink()->appendStylesheet('/adm_template/css/colorpicker.css');
        $this->headLink()->appendStylesheet('/adm_template/css/style.css');
        $this->headLink()->appendStylesheet('/adm_template/css/jquery.autocomplete.css');
        ?>
        <?php
        if ($this->layout()->ckeditor) {
            echo $this->headScript()->appendFile($this->baseUrl() . '/adm_template/js/ckeditor/ckeditor.js');
        }
        ?>
        <meta name="msapplication-starturl" content="<?= $this->baseUrl(); ?>" />


        <?php
        echo $this->headMeta();
        $this->headScript()->appendFile('/adm_template/js/jquery.js');
        $this->headScript()->appendFile('/adm_template/js/atomic.jquery.js');
        $this->headScript()->appendFile('/adm_template/js/jquery.fancybox-1.3.4.js');
        $this->headScript()->appendFile('/adm_template/js/jquery.easing-1.3.pack.js');
        $this->headScript()->appendFile('/adm_template/js/jquery.mousewheel-3.0.4.pack.js');
        $this->headScript()->appendFile('/adm_template/js/jquery-ui-1.8.16.custom.min.js');
        $this->headScript()->appendFile('/adm_template/js/jquery.skinned-select.js');
        $this->headScript()->appendFile('/adm_template/js/colorpicker.js');


        $this->headScript()->appendFile('/adm_template/js/jquery.ui.nestedSortable.js');
        $this->headScript()->appendFile('/adm_template/js/jquery.autocomplete.js');
        $this->headScript()->appendFile('/adm_template/js/plugins/swfupload.js');
        $this->headScript()->appendFile('/adm_template/js/plugins/swfupload.swfobject.js');
        $this->headScript()->appendFile('/adm_template/js/plugins/swfupload.queue.js');
        $this->headScript()->appendFile('/adm_template/js/plugins/handler.js');


        $this->headScript()->appendFile('/adm_template/js/uds_admin.js');
        $this->headScript()->appendFile('/adm_template/js/layout.js');
        $this->headScript()->appendFile('/adm_template/js/script.js');
        ?>

        <?php echo $this->HeadScript(); ?>
        <?php echo $this->magicHeadLink(); ?>
        <!--[if IE]><link rel="stylesheet" type="text/css" href="/adm_template/css/ie.css" /><![endif]-->
        <!--[if IE 6]><link rel="stylesheet" type="text/css" href="/adm_template/css/ie6.css" /><![endif]-->
        <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    </head>
    <body>
        <?
        $auth     = Zend_Auth::getInstance();
        $identity = $auth->getIdentity();
        ?>
        <? if (!isset($identity) || ($identity->role_users == 'user')): ?>

            <?php echo $this->layout()->content ?>

        <? else: ?>
            <div id="lag-menu">
                <ul id="menu-lang">
                    <li <? if (Zend_Registry::get('uds_lang') == 'ru'): ?>class="active"<? endif; ?>><a href="<?= $this->baseUrl(); ?>/ru/admin/" ><img src="adm_template/i/flags/ru.png" width="16" height="16" alt="" /></a></li>
                    <li <? if (Zend_Registry::get('uds_lang') == 'en'): ?>class="active"<? endif; ?>><a href="<?= $this->baseUrl(); ?>/en/admin/"><img src="adm_template/i/flags/gb.png" width="16" height="16" alt="" /></a></li>
                    <li <? if (Zend_Registry::get('uds_lang') == 'ua'): ?>class="active"<? endif; ?>><a href="<?= $this->baseUrl(); ?>/ua/admin/"><img src="adm_template/i/flags/ua.png" width="16" height="16" alt="" /></a></li>
                </ul>


            </div>
            <div id="wrap">
                <? if ($identity->password_users == '202cb962ac59075b964b07152d234b70'): ?>
                    <div class="block-notice">
                        Уважаемый владелец сайта, вы используете стандартный пароль. <br />
                        Если разработка сайта закончена — <a href="admin/configs/pass/">смените</a> этот пароль. В случае обращения в Украинскую студию дизайна с доработками — сообщите свой пароль.
                    </div>
                <? endif; ?>
                <? $this->MakeAdminMenu(); ?>
                <?php echo $this->layout()->content ?>
            </div>
            <div class="clear"></div>
            <div id="copy">
                <img src="adm_template/i/logoUDS_copy.png" alt="UDS" />&copy; Ukrainian Design Studio 2009—<?= date('Y'); ?>
            </div>

        <? endif; ?>

    </body>
</html>
